apps/bautismo/urls.py
from django.urls import path

from .views import HomeView, MinistroList, MinistroCreate, MinistroUpdate, LibroList, LibroCreate, LibroUpdate, \
    ActaList, ActaCreate, ActaUpdate, actaToPdf, setMinistroDefault

app_name = 'bautismo'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),

    path('ministros/', MinistroList.as_view(), name='ministros-list'),
    path('ministros/nuevo', MinistroCreate.as_view(), name='ministros-nuevo'),
    path('ministros/editar/<int:pk>', MinistroUpdate.as_view(), name='ministros-editar'),
    path('actas/set-default/<int:pk>', setMinistroDefault, name='ministros-default'),

    path('libros/', LibroList.as_view(), name='libros-list'),
    path('libros/nuevo', LibroCreate.as_view(), name='libros-nuevo'),
    path('libros/editar/<int:pk>', LibroUpdate.as_view(), name='libros-editar'),

    path('actas/', ActaList.as_view(), name='actas-list'),
    path('actas/nuevo', ActaCreate.as_view(), name='actas-nuevo'),
    path('actas/editar/<int:pk>', ActaUpdate.as_view(), name='actas-editar'),
    path('actas/pdf/<int:pk>', actaToPdf, name='acta-pdf'),

]

iglesia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.bautismo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

apps/bautismo/models.py
from django.db import models

SEXOS_LIST = [
    ('F', 'Femenino'),
    ('M', 'Masculino'),
]


class TimestampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class TipoMinistro(models.Model):
    nombre = models.CharField(max_length=50)
    abreviatura = models.CharField(max_length=10)

    def __str__(self):
        return self.nombre


class Ministro(TimestampModel):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    tipo = models.ForeignKey(TipoMinistro, on_delete=models.SET_NULL, null=True)
    activo = models.BooleanField(default=False)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)

    @property
    def full_name(self):
        return '%s %s' % (self.nombre, self.apellido)

    class Meta:
        ordering = ["nombre"]


class Libro(TimestampModel):
    nombre = models.CharField(max_length=50)
    activo = models.BooleanField(default=False)
    f_inicio = models.DateField('Fecha Inicio', blank=True, null=True)
    f_fin = models.DateField('Fecha Fin', blank=True, null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ["nombre"]


class Acta(TimestampModel):
    libro = models.ForeignKey(Libro, on_delete=models.SET_NULL, blank=True, null=True, )
    folio = models.IntegerField()
    num = models.IntegerField(blank=True, null=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    sexo = models.CharField(max_length=1, choices=SEXOS_LIST)
    f_nacimiento = models.DateField('Fecha de nacimiento', blank=True, null=True)
    lugar_nacimiento = models.CharField('Lugar de nacimiento', max_length=50, blank=True, null=True)
    cedula = models.CharField(max_length=15, blank=True, null=True)
    padre_nombre = models.CharField('Nombre del padre', max_length=50, blank=True, null=True)
    padre_apellido = models.CharField('Apellido del padre', max_length=50, blank=True, null=True)
    madre_nombre = models.CharField('Nombre de la madre', max_length=50, blank=True, null=True)
    madre_apellido = models.CharField('Apellido de la madre', max_length=50, blank=True, null=True)
    filiacion = models.CharField(max_length=20, blank=True, null=True)
    f_bautizo = models.DateField('Fecha de bautizo')
    padrino_nombre = models.CharField('Nombre del padrino', max_length=50, blank=True, null=True)
    padrino_apellido = models.CharField('Apellido del padrino', max_length=50, blank=True, null=True)
    madrina_nombre = models.CharField('Nombre de la madrina', max_length=50, blank=True, null=True)
    madrina_apellido = models.CharField('Apellido de la madrina', max_length=50, blank=True, null=True)
    ministro = models.ForeignKey(Ministro, on_delete=models.SET_NULL, blank=True, null=True, )
    observacion = models.TextField(blank=True, null=True)
    casado = models.BooleanField(default=False)
    f_matrimonio = models.DateField('Fecha de matrimonio', blank=True, null=True)
    conyugue = models.CharField('Nombre del conyugue', max_length=100, blank=True, null=True)
    parroquia_matrimonio = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return '%s %s' % (self.nombre, self.apellido)

    @property
    def full_name(self):
        return '%s %s' % (self.nombre, self.apellido)

    @property
    def padrino(self):
        return '%s %s' % (self.padrino_nombre, self.padrino_apellido)

    @property
    def madrina(self):
        return '%s %s' % (self.madrina_nombre, self.madrina_apellido)

    @property
    def padre(self):
        return '%s %s' % (self.padre_nombre, self.padre_apellido)

    @property
    def madre(self):
        return '%s %s' % (self.madre_nombre, self.madre_apellido)

    class Meta:
        ordering = ["nombre"]

apps/bautismo/forms.py
from django.forms import ModelForm

from django import forms
from .models import Ministro, Libro, Acta


class MinistroForm(ModelForm):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    apellido = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Apellido'}))

    class Meta:
        model = Ministro
        exclude = ['created_at', 'updated_at', 'activo']


class LibroForm(ModelForm):
    class Meta:
        model = Libro
        exclude = ['created_at', 'updated_at']


class ActaForm(ModelForm):
    class Meta:
        model = Acta
        exclude = ['created_at', 'updated_at']


class ActaSearchForm(forms.Form):
    nombre = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    apellido = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'placeholder': 'Apellido'}))
    f_bautizo = forms.DateField(required=False, label='Fecha de Bautizo', widget=forms.TextInput(attrs={'placeholder': 'Bautizo'}))

apps/bautismo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from weasyprint import HTML
from weasyprint.fonts import FontConfiguration
from django.http import HttpResponse
from django.utils.text import slugify
from django.conf import settings
from django.template.loader import render_to_string
from .models import Ministro, Libro, Acta
from .forms import MinistroForm, LibroForm, ActaForm, ActaSearchForm
import datetime


class HomeView(TemplateView):
    template_name = "index.html"


class MinistroList(ListView):
    model = Ministro
    ordering = ('nombre', 'apellido',)


class MinistroCreate(SuccessMessageMixin, CreateView):
    model = Ministro
    form_class = MinistroForm
    success_url = reverse_lazy('bautismo:ministros-list')
    success_message = "Ministro creado con exito"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = 'Nuevo ministro'
        return context


class MinistroUpdate(SuccessMessageMixin, UpdateView):
    model = Ministro
    form_class = MinistroForm
    success_url = reverse_lazy('bautismo:ministros-list')
    success_message = "Ministro actualizado con exito"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = 'Editar ministro'
        return context


class LibroList(ListView):
    model = Libro
    ordering = ('nombre',)


class LibroCreate(SuccessMessageMixin, CreateView):
    model = Libro
    form_class = LibroForm
    success_url = reverse_lazy('bautismo:libros-list')
    success_message = "Libro creado con exito"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = 'Nuevo libro'
        return context


class LibroUpdate(SuccessMessageMixin, UpdateView):
    model = Libro
    form_class = LibroForm
    success_url = reverse_lazy('bautismo:libros-list')
    success_message = "Libro actualizado con exito"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = 'Editar libro'
        return context


class ActaList(ListView):
    model = Acta
    ordering = ('nombre', 'apellido',)
    paginate_by = 15
    form = ActaSearchForm

    def get_queryset(self):
        queryset = Acta.objects.all()
        form_search = self.form(self.request.GET)
        if form_search.is_valid():
            data = form_search.cleaned_data
            if data['nombre']:
                queryset = queryset.filter(nombre=data['nombre'])
            if data['apellido']:
                queryset = queryset.filter(apellido=data['apellido'])
            if data['f_bautizo']:
                queryset = queryset.filter(f_bautizo=data['f_bautizo'])
        else:
            print('formulario no válido')
        return queryset

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['form_search'] = self.form(self.request.GET)
        return context


class ActaCreate(SuccessMessageMixin, CreateView):
    model = Acta
    form_class = ActaForm
    success_url = reverse_lazy('bautismo:actas-list')
    success_message = "Acta de bautismo creado con exito"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = 'Agregar acta de bautismo'
        return context


class ActaUpdate(SuccessMessageMixin, UpdateView):
    model = Acta
    form_class = ActaForm
    success_url = reverse_lazy('bautismo:actas-list')
    success_message = "Acta de bautismo actualizado con exito"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['title'] = 'Editar acta de bautismo'
        return context


def actaToPdf(request, pk):
    # return render(request, 'bautismo/acta_pdf.html')
    acta = get_object_or_404(Acta, pk=pk)
    hoy = datetime.date.today()
    ministro = get_object_or_404(Ministro, activo=True)
    namefile = slugify('bautismo ' + acta.apellido + ' ' + acta.nombre)
    # response['Content-Disposition'] = "inline; filename={namefile}.pdf".format(
    response = HttpResponse(content_type="application/pdf")
    response['Content-Disposition'] = "inline; filename={namefile}.pdf".format(namefile=namefile)
    html = render_to_string("bautismo/acta_pdf.html", {'acta': acta, 'hoy': hoy, 'ministro': ministro})
    font_config = FontConfiguration()
    HTML(string=html, base_url=request.build_absolute_uri()).write_pdf(response, font_config=font_config)
    return response


def setMinistroDefault(request, pk):
    ministros = Ministro.objects.all()
    for ministro in ministros:
        if ministro.pk == pk:
            ministro.activo = True
        else:
            ministro.activo = False
        ministro.save()
    return redirect(reverse_lazy('bautismo:ministros-list'))

apps/bautismo/templates/bautismo/acta_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>{{title}}</h2>
<form action="" method="post">
  {% csrf_token %}
  <div class="row">
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.libro|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.folio|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.f_bautizo|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.ministro|as_crispy_field }}
    </div>
    <div class="col-12">
      <h5>Datos del bautizado(a)</h5>
      <hr>
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.nombre|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.apellido|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.sexo|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.f_nacimiento|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.lugar_nacimiento|as_crispy_field }}
    </div>
    <div class="col-12">
      <h5>Datos de los Padres</h5>
      <hr>
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.padre_nombre|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.padre_apellido|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.madre_nombre|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.madre_apellido|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.filiacion|as_crispy_field }}
    </div>
    <div class="col-12">
      <hr>
    </div>
    <div class="col-12">
      <h5>Datos de los Padrinos</h5>
      <hr>
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.padrino_nombre|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.padrino_apellido|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.madrina_nombre|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
      {{ form.madrina_apellido|as_crispy_field }}
    </div>
    <div class="col-12">
      <hr>
    </div>
    <div class="form-group col-12 mb-0">
      {{ form.observacion|as_crispy_field }}
    </div>

  </div>
  <div class="row">
    <div class="col-12">
      <button type="submit" class="btn btn-outline-primary">Guardar</button>
    </div>
  </div>
</form>
{% endblock%}

{% block css %}
{{block.super}}
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block js %}
{{block.super}}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>

<script>
  $('#id_f_nacimiento').datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd/mm/yyyy'
  });
  $('#id_f_bautizo').datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd/mm/yyyy'
  });
</script>
{% endblock %}

apps/bautismo/templates/bautismo/acta_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block content %}
<h2>Acta de bautismo</h2>

<div class="row">
  <div class="col-12">
    <a href="{% url 'bautismo:actas-nuevo' %}" class="btn btn-primary">Agregar</a>
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseSearch"
            aria-expanded="false" aria-controls="collapseExample">
      Filtrar
    </button>
    <form action="" method="get" class="bg-light p-3 mt-3 collapse" id="collapseSearch">
      <div class="row">
              <div class="col-12">
        <h5 class="">Filtrar</h5>
      </div>
      <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
        {% crispy_field form_search.nombre 'class' 'form-control' %}
      </div>
      <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
        {% crispy_field form_search.apellido 'class' 'form-control' %}
      </div>
      <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
        {% crispy_field form_search.f_bautizo 'class' 'form-control' %}
      </div>
      <div class="form-group col-sm-6 col-md-4 col-lg-3 mb-0">
        <button type="submit" class="btn btn-outline-primary">Buscar</button>
      </div>

      </div>
    </form>
  </div>
  <div class="col-12 table-responsive">
    <table class="table mt-3">
      <thead>
      <tr>
        <th class="text-center">Libro</th>
        <th class="text-center">Folio</th>
        <th class="text-center">Nombre</th>
        <th class="text-center">Apellido</th>
        <th class="text-center">F. Nac</th>
        <th class="text-center">F. Bautizo</th>
        <th class="text-center">Acciones</th>
      </tr>
      </thead>
      <tbody>
      {% for acta in object_list %}
      <tr>
        <td class="text-center">{{acta.libro}}</td>
        <td class="text-center">{{acta.folio}}</td>
        <td>{{acta.nombre}}</td>
        <td>{{acta.apellido}}</td>
        <td class="text-center">{{acta.f_nacimiento|default_if_none:"-"}}</td>
        <td class="text-center">{{acta.f_bautizo|default_if_none:"-"}}</td>
        <td class="text-center">
          <a href="{% url 'bautismo:acta-pdf' acta.pk %}" target="_blank" class="btn btn-sm btn-outline-info">PDF</a>
          <a href="{% url 'bautismo:actas-editar' acta.pk %}" class="btn btn-sm btn-outline-primary">Editar</a>
          <!--<button type="button" class="btn btn-sm btn-outline-danger">Eliminar</button>-->
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

{% block css %}
{{block.super}}
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
{% endblock %}


{% block js %}
{{block.super}}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>

<script>
  $('#id_f_bautizo').datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd/mm/yyyy'
  });
</script>
{% endblock %}

apps/bautismo/templates/bautismo/acta_pdf.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Fe de bautismo - {{acta.nombre|title}} {{acta.apellido|title}}</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <!--<link rel="stylesheet" href="{% static 'css/reset.css' %}">-->
  <!--<link href="https://fonts.googleapis.com/css?family=Rosario&display=swap" rel="stylesheet">-->
  <!--<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">-->
  <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
  <style>
    * {
      /*font-family: sans-serif;*/
      /*font-family: 'Rosario', sans-serif;*/
      /*font-family: 'Roboto', sans-serif;*/
      font-family: 'Rubik', sans-serif;
    }
    @page {
      size: Letter;
      margin: 1.5cm;
      /*border: 1px solid #e2e3e5;*/
    }

    p {
      font-size: 12pt;
    }

    #header {
      /*border: 1px solid #e2e3e5;*/
      text-align: center;
      text-transform: uppercase;
      width: 18.59cm;
    }

    #body {
      /*border: 1px solid #e2e3e5;*/
      width: 18.59cm;
      font-size: 12pt;
    }
  </style>
</head>
<body>
<section id="header">
  <img src="{% static 'img/nsdc.jpg' %}" alt="logo"
       style="position: absolute; left: 0; top: 0; height: 100px; width: 100px">
  <h5 class="text-cent">DIOCESIS DE CIUDAD GUAYANA - VENEZUELA<br>
    PUERTO ORDAZ - EDO.BOLIVAR<br>
    PARROQUIA NTRA. SRA. DE COROMOTO
  </h5>
</section>
<section id="body" class="mt-5">
  <div class="d-flex">
    <div class="w-25">
      <div class="col-12 text-uppercase mt-3 pl-0">
        <p class="mb-0">
          Libro: {{acta.libro}}<br>
          Folio: {{acta.folio}}<br>
          Num: 4<br>
        </p>
      </div>

      <div class="col-12 pl-0" style="margin-top: 12cm;">
        <h6 class="text-uppercase mb-3">Registro Civil</h6>
        <p class="mb-0">Fue presentado: <br>
          Acta N°: 101<br>
          Folio: 100<br>
          Libro: 100<br>
          Año: 1999
        </p>
      </div>
    </div>

    <div class="w-75" style="border-left: 1px solid #b1b1b1; border-radius: 0;">
      <div class="col-12">
        <h5 class="text-center mb-3">CERTIFICADO DE BAUTISMO</h5>
        <p class="text-left">El {{ ministro.tipo.nombre }} <b>{{ministro.full_name|title}}</b>,
          Párroco de esta Parroquia
          certifica que según consta en Acta reseñada al margen,
          correspondiente al libro de Bautismo</p>

        <h5 class="font-weight-bold">{{acta.full_name|title}}</h5>
        <p class="mt-3"><b>Nacido en:</b> {{acta.lugar_nacimiento|title}}</p>
        <p><b>Fue bautizado el:</b> {{acta.f_bautizo|date}}</p>
        <p><b>Padres:</b> <br>{{acta.padre|title}} <br> {{acta.madre|title}}</p>
        <p><b>Padrinos:</b> <br>{{acta.padrino|title}} <br> {{acta.madrina|title}}</p>
        <p><b>Ministro:</b> <br>{{ acta.ministro.tipo.nombre }} {{acta.ministro.full_name|title}}</p>
        <p style="margin-top: 1.3cm">
          <small>Se expide el presente certificado para fines de: DOCUMENTOS</small>
          <br>
          Puerto Ordaz, {{hoy|date}} <br>
        Doy Fe,</p>
        <p class="text-center text-uppercase">_________________________ <br>
          {{ ministro.tipo.abreviatura }}. {{ministro.full_name}}
        </p>
      </div>
    </div>
  </div>
  <div class="d-flex mt-3">
    <div class="w-25"></div>
    <div class="w-75 float-right pt-2">
      <div class="col-12">
        <p class="text-cursive mb-1">Dirección: Calle Vigo, Los Olivos,
          Puerto Ordaz, Edo Bolívar <br>
          Teléfono: 0286-9617002
        </p>
        <p class="text-uppercase mb-0">si este certificado va a ser utilizado fuera de la diócesis debe ser autenticado
          en la
          curia diocesana</p>
      </div>
    </div>
  </div>
</section>
</body>
</html>

apps/bautismo/templates/bautismo/libro_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>{{title}}</h2>
<form action="" method="post">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      {{ form|crispy }}
      <button type="submit" class="btn btn-outline-primary">Guardar</button>
    </div>
  </div>
</form>
{% endblock%}

{% block css %}
{{block.super}}
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block js %}
{{block.super}}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>

<script>
  $('#id_f_inicio').datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd/mm/yyyy'
  });
  $('#id_f_fin').datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd/mm/yyyy'
  });
</script>
{% endblock %}

apps/bautismo/templates/bautismo/libro_list.html
{% extends "base.html" %}

{% block content %}
<h2>Libros</h2>

<div class="row">
  <div class="col-12">
    <a href="{% url 'bautismo:libros-nuevo' %}" class="btn btn-primary">Agregar</a>
  </div>
  <div class="col-12 table-responsive">
    <table class="table mt-3">
      <thead>
      <tr>
        <th class="text-center">Nombre</th>
        <th class="text-center">Fecha inicio</th>
        <th class="text-center">Fecha fin</th>
        <th class="text-center">Estado</th>
        <th class="text-center">Acciones</th>
      </tr>
      </thead>
      <tbody>
      {% for libro in object_list %}
      <tr>
        <td>{{libro.nombre}}</td>
        <td class="text-center">{{libro.f_inicio|default_if_none:"-"}}</td>
        <td class="text-center">{{libro.f_fin|default_if_none:"-"}}</td>
        <td class="text-center">{% if libro.activo%}<span class="badge badge-success">Activo</span>
          {% else %}<span class="badge badge-danger">Inactivo</span>{% endif %}
        </td>
        <td class="text-center">
          <a href="{% url 'bautismo:libros-editar' libro.pk %}" class="btn btn-sm btn-outline-primary">Editar</a>
          <button type="button" class="btn btn-sm btn-outline-danger">Eliminar</button>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

apps/bautismo/templates/bautismo/ministro_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>{{title}}</h2>
<form action="" method="post">
  {% csrf_token %}
  <div class="row">
    <div class="form-group col-sm-6 mb-0">
      {{ form.nombre|as_crispy_field }}
    </div>
    <div class="form-group col-sm-6 mb-0">
      {{ form.apellido|as_crispy_field }}
    </div>

    <div class="form-group col-12">
      <button type="submit" class="btn btn-outline-primary">Guardar</button>
    </div>
  </div>
</form>
{% endblock%}

apps/bautismo/templates/bautismo/ministro_list.html
{% extends "base.html" %}

{% block content %}
<h2>Ministros</h2>

<div class="row">
  <div class="col-12">
    <a href="{% url 'bautismo:ministros-nuevo' %}" class="btn btn-primary">Agregar</a>
  </div>
  <div class="col-12 table-responsive">
    <table class="table mt-3">
      <thead>
      <tr>
        <th class="text-center">Nombre</th>
        <th class="text-center">Apellido</th>
        <th class="text-center">Estado</th>
        <th class="text-center">Acciones</th>
      </tr>
      </thead>
      <tbody>
      {% for ministro in object_list %}
      <tr>
        <td>{{ministro.nombre}}</td>
        <td>{{ministro.apellido}}</td>
        <td class="text-center">{% if ministro.activo%}<span class="badge badge-success">Activo</span>
          {% else %}<span class="badge badge-danger">Inactivo</span>{% endif %}
        </td>
        <td class="text-center">
          {% if not ministro.activo %}
          <a href="{% url 'bautismo:ministros-default' ministro.pk %}" class="btn btn-sm btn-outline-success">Activar</a>
          {% endif %}
          <a href="{% url 'bautismo:ministros-editar' ministro.pk %}" class="btn btn-sm btn-outline-primary">Editar</a>
          <!--<button type="button" class="btn btn-sm btn-outline-danger">Eliminar</button>-->
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}