apps/bautismo/urls.py
from django.urls import path

from .views import HomeView, MinistroList, MinistroCreate, MinistroUpdate, LibroList, LibroCreate, LibroUpdate, \
    ActaList, ActaCreate, ActaUpdate, actaToPdf, setMinistroDefault

app_name = 'bautismo'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),

    path('ministros/', MinistroList.as_view(), name='ministros-list'),
    path('ministros/nuevo', MinistroCreate.as_view(), name='ministros-nuevo'),
    path('ministros/editar/<int:pk>', MinistroUpdate.as_view(), name='ministros-editar'),
    path('actas/set-default/<int:pk>', setMinistroDefault, name='ministros-default'),

    path('libros/', LibroList.as_view(), name='libros-list'),
    path('libros/nuevo', LibroCreate.as_view(), name='libros-nuevo'),
    path('libros/editar/<int:pk>', LibroUpdate.as_view(), name='libros-editar'),

    path('actas/', ActaList.as_view(), name='actas-list'),
    path('actas/nuevo', ActaCreate.as_view(), name='actas-nuevo'),
    path('actas/editar/<int:pk>', ActaUpdate.as_view(), name='actas-editar'),
    path('actas/pdf/<int:pk>', actaToPdf, name='acta-pdf'),

]

iglesia/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.bautismo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}Fe de bautizmo{% endblock %}</title>
  {% block head %}{% endblock %}


  {% block css %}
  <!-- Bootstrap CSS -->
  <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <style>
    * {
      font-family: 'Rubik', sans-serif;
    }
  </style>
  {% endblock %}
</head>
<body>
{% include 'menu.html' %}
<div class="container pt-3 pb-5">
  {% include 'messages.html' %}
  {% block content %}{% endblock %}
</div>

{% block js %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="jumbotron">
  <h1>Navbar example</h1>
  <p class="lead">This example is a quick exercise to illustrate how fixed to top navbar works. As you scroll, it will
    remain fixed to the top of your browser’s viewport.</p>
  <a class="btn btn-lg btn-primary" href="/docs/4.3/components/navbar/" role="button">View navbar docs &raquo;</a>
</div>

{% endblock %}

templates/menu.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">PNSDC</a>

    {% if user.is_authenticated %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
<!--
        <li class="nav-item">
          <a class="nav-link" href="/">Inicio</a>
        </li>
-->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bautismo:actas-list' %}">Actas de Bautizmo</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            Configuración
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'bautismo:libros-list'%}">Libros</a>
            <a class="dropdown-item" href="{% url 'bautismo:ministros-list'%}">Ministros</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Otros</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>

      </ul>
      <!--
            <form class="form-inline mt-2 mt-md-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Buscar" aria-label="Buscar">
              <button class="btn btn-primary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
      -->
    </div>
    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>

    </ul>
    {% endif %}
  </div>
</nav>

templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}